### ISSUE TITLE
gst_queue_loop/gst_opus_dec_negotiate crash, N=2 native fedora22

### ISSUE THREAD

**Issue by jhgorse** [jhgorse/onevideo#16]
Starting a new call. Occurs intermittently.
May be related to [issue 8 ](https://github.com/jhgorse/onevideo/issues/8).

```
(gdb) bt
#0  0x00007ffff4b2ed3b in g_logv (breakpoint=1) at gmessages.c:315
#1  0x00007ffff4b2ed3b in g_logv (log_domain=0x7ffff77533f0 <g_log_domain_gstreamer> "GStreamer", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fff997f9310)
    at gmessages.c:1041
#2  0x00007ffff4b2eeaf in g_log (log_domain=<optimized out>, log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff4b9e95d "%s: assertion '%s' failed") at gmessages.c:1079
#3  0x00007ffff4b2eee9 in g_return_if_fail_warning (log_domain=<optimized out>, pretty_function=pretty_function@entry=0x7ffff7758c40 <__func__.19847> "gst_caps_get_structure", expression=expression@entry=0x7ffff775851b "index < GST_CAPS_LEN (caps)") at gmessages.c:1088
#4  0x00007ffff76cd99a in gst_caps_get_structure (caps=caps@entry=0x7fff940021e0, index=index@entry=0) at gstcaps.c:819
#5  0x00007fffd257729c in gst_opus_dec_negotiate (dec=dec@entry=0x8942c0 [GstOpusDec], pos=0x0) at gstopusdec.c:238
#6  0x00007fffd2578d95 in gst_opus_dec_set_format (bdec=<optimized out>, caps=0x7fff900028f0) at gstopusdec.c:691
#7  0x00007fffdcaba280 in gst_audio_decoder_sink_eventfunc (caps=0x7fff900028f0, dec=0x8942c0 [GstOpusDec]) at gstaudiodecoder.c:864
#8  0x00007fffdcaba280 in gst_audio_decoder_sink_eventfunc (dec=0x8942c0 [GstOpusDec], event=0x7fffb4002900) at gstaudiodecoder.c:2265
#9  0x00007ffff76f79b7 in gst_pad_send_event_unchecked (pad=pad@entry=0xc97b40 [GstPad], event=event@entry=0x7fffb4002900, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at gstpad.c:5554
#10 0x00007ffff76f7dc6 in gst_pad_push_event_unchecked (pad=pad@entry=0xc97240 [GstPad], event=0x7fffb4002900, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5212
#11 0x00007ffff76f8200 in push_sticky (pad=pad@entry=0xc97240 [GstPad], ev=ev@entry=0x7fff997f9820, user_data=user_data@entry=0x7fff997f9880) at gstpad.c:3757
#12 0x00007ffff76f5f97 in events_foreach (pad=pad@entry=0xc97240 [GstPad], func=func@entry=0x7ffff76f80b0 <push_sticky>, user_data=user_data@entry=0x7fff997f9880) at gstpad.c:598
#13 0x00007ffff77021d4 in gst_pad_push_event (event=0x7fffb4002900, pad=0xc97240 [GstPad]) at gstpad.c:3814
#14 0x00007ffff77021d4 in gst_pad_push_event (pad=pad@entry=0xc97240 [GstPad], event=0x7fffb4002900) at gstpad.c:5343
#15 0x00007fffd257e12b in gst_rtp_opus_depay_setcaps (caps=0x7fff900028f0, pad=0xc97240 [GstPad]) at /home/jhg/gst/master/gstreamer/gst/gstcompat.h:58
#16 0x00007fffd257e12b in gst_rtp_opus_depay_setcaps (depayload=0x8c16f0 [GstRTPOpusDepay], caps=<optimized out>) at gstrtpopusdepay.c:130
#17 0x00007fffd2796791 in gst_rtp_base_depayload_handle_event (caps=0x7fff880028f0, filter=0x8c16f0 [GstRTPOpusDepay]) at gstrtpbasedepayload.c:325
#18 0x00007fffd2796791 in gst_rtp_base_depayload_handle_event (filter=0x8c16f0 [GstRTPOpusDepay], event=0x7fff9c003ed0) at gstrtpbasedepayload.c:597
#19 0x00007ffff76f79b7 in gst_pad_send_event_unchecked (pad=pad@entry=0xc97480 [GstPad], event=event@entry=0x7fff9c003ed0, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at gstpad.c:5554
#20 0x00007ffff76f7dc6 in gst_pad_push_event_unchecked (pad=pad@entry=0xb19b50 [GstPad], event=0x7fff9c003ed0, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5212
#21 0x00007ffff76f8200 in push_sticky (pad=pad@entry=0xb19b50 [GstPad], ev=ev@entry=0x7fff997f9b10, user_data=user_data@entry=0x7fff997f9b70) at gstpad.c:3757
#22 0x00007ffff76f5f97 in events_foreach (pad=pad@entry=0xb19b50 [GstPad], func=func@entry=0x7ffff76f80b0 <push_sticky>, user_data=user_data@entry=0x7fff997f9b70) at gstpad.c:598
#23 0x00007ffff77021d4 in gst_pad_push_event (event=0x7fff9c003ed0, pad=0xb19b50 [GstPad]) at gstpad.c:3814
#24 0x00007ffff77021d4 in gst_pad_push_event (pad=0xb19b50 [GstPad], event=event@entry=0x7fff9c003ed0) at gstpad.c:5343
#25 0x00007fffdc62d153 in gst_queue_loop (queue=0xc9cc40 [GstQueue]) at gstqueue.c:1410
#26 0x00007fffdc62d153 in gst_queue_loop (pad=<optimized out>) at gstqueue.c:1487
#27 0x00007ffff772ac21 in gst_task_func (task=0xd11a70 [GstTask]) at gsttask.c:332
#28 0x00007ffff4b4fa3e in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:307
#29 0x00007ffff4b4f0a5 in g_thread_proxy (data=0xcfb770) at gthread.c:764
#30 0x00007ffff48c8555 in start_thread (arg=0x7fff997fa700) at pthread_create.c:333
#31 0x00007ffff4602ded in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

```
0:00:42.209810195 17281       0x647c10 DEBUG               onevideo onevideo/lib.c:1432:ov_local_peer_call_start: Ready to playback data from all remotes
0:00:43.021473837 17281       0xcfb770 WARN                   pulse pulsesink.c:2173:gst_pulsesink_query_getcaps:<pulsesink0> Could not create probe stream

(OneVideo:17281): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'index < GST_CAPS_LEN (caps)' failed
```

**Comment by jhgorse** [comment]
The top of the call stack appears to be equivalent to issue 8's.

**Comment by nirbheek** [comment]
I haven't been able to reproduce this one. Joe, could you try to reproduce this again since commit 8406cd56?

**Comment by jhgorse** [comment]
Confirmed resolved after extensive testing. =)
