### ISSUE TITLE
Linux crash for invalid -d video device instead of using testsrc

### ISSUE THREAD

**Issue by jhgorse** [jhgorse/onevideo#25]
./debug-one-video-gui.sh -i wlp4s0 -p 6000 -d test
./debug-one-video-cli.sh -i wlp4s0 -d /dev/video0

Gui output and backtrace

```
0:00:15.083388177 12647       0xb4ef70 DEBUG               onevideo onevideo/outgoing.c:789:ov_remote_peer_tcp_client_start_call: Recvd from 'omega.local:5000-c2d905b763b994ef3848c030578450ed' ACK
Negotiation finished, starting call
Detaching after fork from child process 12672.
Running under Mesa OpenGL which is buggy when using multiple GL contexts. Falling back to software rendering.

(OneVideo:12647): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
[New Thread 0x7fffdab63700 (LWP 12669)]
[New Thread 0x7fffdbf77700 (LWP 12652)]

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff43f7d3b in _g_log_abort (breakpoint=1) at gmessages.c:315
315     G_BREAKPOINT ();
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-14.fc22.x86_64 flac-libs-1.3.1-5.fc22.x86_64
(gdb) bt
#0  0x00007ffff43f7d3b in g_logv (breakpoint=1) at gmessages.c:315
#1  0x00007ffff43f7d3b in g_logv (log_domain=0x7ffff471bb84 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffb0b0) at gmessages.c:1041
#2  0x00007ffff43f7eaf in g_log (log_domain=log_domain@entry=0x7ffff471bb84 "GLib-GObject", log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff446795d "%s: assertion '%s' failed") at gmessages.c:1079
#3  0x00007ffff43f7ee9 in g_return_if_fail_warning (log_domain=log_domain@entry=0x7ffff471bb84 "GLib-GObject", pretty_function=pretty_function@entry=0x7ffff471f138 <__func__.13167> "g_object_set", expression=expression@entry=0x7ffff471dcd0 "G_IS_OBJECT (object)") at gmessages.c:1088
#4  0x00007ffff46f8d09 in g_object_set (_object=0x0, first_property_name=0x7ffff7bd4eeb "device-index") at gobject.c:2265
#5  0x00007ffff7bc5dd2 in ov_local_peer_setup_transmit_pipeline (local=0x9f7150 [OvLocalPeer]) at onevideo/ov-local-peer-setup.c:357
#6  0x00007ffff7bcc1a1 in ov_local_peer_call_start (local=0x9f7150 [OvLocalPeer]) at onevideo/lib.c:1443
#7  0x0000000000406a6f in wrapper_setup_peers_video (win=0xa643b0 [OvgAppWindow]) at gui/ovg-appwin.c:706
#8  0x00007ffff43f0a8a in g_main_context_dispatch (context=0x668a80) at gmain.c:3122
#9  0x00007ffff43f0a8a in g_main_context_dispatch (context=context@entry=0x668a80) at gmain.c:3737
#10 0x00007ffff43f0e20 in g_main_context_iterate (context=context@entry=0x668a80, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3808
#11 0x00007ffff43f0ecc in g_main_context_iteration (context=0x668a80, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:3869
#12 0x00007ffff49dc26c in g_application_run (application=0x634100 [OvgApp], argc=7, argv=0x7fffffffb6b8) at gapplication.c:2308
#13 0x0000000000407c04 in main (argc=7, argv=0x7fffffffb6b8) at gui/ovg-main.c:74
```

**Comment by jhgorse** [comment]
My Mac OS hack left in. Cruft.
